### ISSUE TITLE
only the readings from time of the upload are shown

### ISSUE THREAD

**Issue by taisau** [pimoroni/enviro#105]
Intermediate data readings are not shown when posting to influxdb and viewing with grafana. Only readings from the time of the upload are shown. I suspect the timestamps in the readings files are not used or invalid, so influxdb assigns its timestamp to all the files uploaded at one time.

**Comment by MrDrem** [comment]
This is resolved by commit [d8da4d3 ](https://github.com/pimoroni/enviro/commit/d8da4d3606c492769443e274d0a99964df8c1ea5) and mentioned in issue #73
