### ISSUE TITLE
picow-enviro firmware not listed

### ISSUE THREAD

**Issue by lleibovici** [pimoroni/enviro#13]
The update firmware documentation shows two versions of the picow firmware one for the envoro series, but that one is not listed on the current releases page.

**Comment by helgibbons** [comment]
Hello! Are you looking at the latest releases page? It won't show up on 'latest' as v1.19.7 is tagged as a pre-release - this link should show you all releases:

https://github.com/pimoroni/pimoroni-pico/releases

**Comment by lleibovici** [comment]
Ahh I did not click on Assets under 19.7. See it now. Thanks
