### ISSUE TITLE
Grow sensors do not report correctly

### ISSUE THREAD

**Issue by sgtwilko** [pimoroni/enviro#14]
Hi,

I've observed two instances of the grow sensors reporting incorrect values:

In this screenshot I had watered only the pot with sensor 1 in it:
![image](https://user-images.githubusercontent.com/658876/184444665-61ae80f9-f62e-4942-9e5d-ea2de7ca2aed.png)
As you can see, sensor 1 stopped reading values, and sensors 2 and 3 showed an increase when there was none.

In this example I watered just pot  with sensor 3 in it:
![image](https://user-images.githubusercontent.com/658876/184444878-e9e5c2c6-fcce-430f-9bc5-edc726352a71.png)
As you can see sensor 2 also showed an increase.

I'm wondering if this is to do with the combined loop over all sensors when measuring the times.

Edit:
Example one, subsequently updated to report like this:
![Screenshot_20220812-230006~2](https://user-images.githubusercontent.com/658876/184451464-c3f619f4-24c0-4dac-8bf7-7c43891e958c.png)

**Comment by ThisIsBenny** [comment]
I have also sometimes the feeling that wrong datas are reported 😔

Examples where I have some times data reported which total out of the average and not realistic (50 Celsius): 
![image](https://user-images.githubusercontent.com/66417262/184942627-a0aee614-fce2-41a1-88ff-d8e7d0ee4155.png)
![image](https://user-images.githubusercontent.com/66417262/184943047-0e3acbe5-c879-4e9c-a218-6f68fdaa6313.png)

**Comment by lowfatcode** [comment]
A new way to measure the moisture sensors is in https://github.com/pimoroni/enviro/commit/9ad7574c197e12e2b35dca2c531eaaec959f7e1e

It now measures each sensor independently rather than in a shared loop that could cause contamination of results.
