### ISSUE TITLE
Time Zone

### ISSUE THREAD

**Issue by ellisdeon** [pimoroni/enviro#153]
Allow to change the Time Zone. GMT +2

**Comment by redlegjed** [comment]
How was this fixed?
I want to do GMT -5

**Comment by ellisdeon** [comment]
> How was this fixed? I want to do GMT -5
Sorry I never got an answer,

**Comment by jparshook** [comment]
In logging.py, I made some changes to datetime_string() to adjust for the timezone.

  dt = machine.RTC().datetime()
  timezone = -4
  hour = dt[4] + timezone
  if hour < 0:
      hour += 24
  if hour > 24:
      hour -= 24
  return str(dt[0])+'-'+str(dt[1])+'-'+str(dt[2])+' '+str(hour)+':'+str(dt[5])+':'+str(dt[6])
  #return "{0:04d}-{1:02d}-{2:02d} {4:02d}:{5:02d}:{6:02d}".format(*dt)

I'm sure there's a better way than this, but it seems to work.
