### ISSUE TITLE
Error Uploading to Adafruit IO

### ISSUE THREAD

**Issue by 10750663** [pimoroni/enviro#161]
2023-03-21 13:13:37 [error    /   77216] ! failed to upload '2023-03-21 13:13:24.json' (401 b'Unauthorized') 2023-03-21 13:13:24.json

I have created a group named "enviro" within my feed and linked this to the enviro during set up 

Any ideas why this isn't posting to Adafruit?

**Comment by sjefferson99** [comment]
Unauthorized suggests username or key error.

Double check the config.py file on your device was correctly populated with the username and key from your adafruit account, no typos or leading/trailing spaces etc. as per the [adafruit destination doc](https://github.com/pimoroni/enviro/blob/main/documentation/destinations/adafruit-io.md)
