### ISSUE TITLE
HTTP endpoints: readings deleted on non-200 status code

### ISSUE THREAD

**Issue by tbbuck** [pimoroni/enviro#18]
Hi!

The documentation says that readings will only be deleted if an HTTP endpoint replies with a `200` status code.

My Python's a bit rusty, should line 34 be indented? Looks like readings are deleted no matter what status code is returned :-o

https://github.com/pimoroni/enviro/blob/75ec51567392f772abb587efedd8a928191814cf/enviro/destinations/http.py#L30-L34

(keep up the good work, loving my Enviro!)

EDIT: aha, looks like this pull request fixes things, including possibly a second issue I was investigating (requests fail after sending 3 readings): https://github.com/pimoroni/enviro/pull/15

**Comment by lowfatcode** [comment]
This has been fixed - thanks for pointing it out! https://github.com/pimoroni/enviro/commit/cafed0633d290945bcefeb4827051df16c860ac8
