### ISSUE TITLE
If your mqtt broker goes down, the board gets stuck in connecting forever

### ISSUE THREAD

**Issue by Godley** [pimoroni/enviro#28]
If your mqtt config is either not right (e.g bad hostname), or your broker goes down, the board's activity light remains on forever (I'm presuming it's stuck). The only way to resolve the latter issue is to power it off and back on again once your broker is back up (or figure out the config is wrong for yourself).

**Comment by lowfatcode** [comment]
I've added a 30 second timeout to the MQTT client so this shouldn't happen any more! Fixed in https://github.com/pimoroni/enviro/commit/4ec6b426325971dde7629eca90f45933bcd86688
