### ISSUE TITLE
Warning LED not working

### ISSUE THREAD

**Issue by helgibbons** [pimoroni/enviro#30]
When given incorrect wifi details, the code in `main.py` that's meant to flash the warning LED instead throws an Attribute Error:

<img width="655" alt="image" src="https://user-images.githubusercontent.com/50950368/186481081-8b92be7a-c3d1-4078-879c-433c271149a8.png">

**Comment by lowfatcode** [comment]
Fixed in https://github.com/pimoroni/enviro/commit/f078ee1658c8c908b29fe53f16b3b967ccb46213
