### ISSUE TITLE
VOC

### ISSUE THREAD

**Issue by emmanorling** [pimoroni/enviro#34]
My main motivation in getting the enviro indoor was to monitor VOC, but the provided software doesn't seem to do this. Any chance this will be in a near update?

**Comment by Zasari** [comment]
For me as-well, I don't see any data from the VOC in the MQTT Json (tested as-well with 0.0.3 beta) on two enviro/indoor. Or did I miss some setting?

**Comment by lowfatcode** [comment]
Thanks both! Please take a look at https://github.com/pimoroni/enviro/pull/58

This will be in our upcoming v0.0.7 release which we recommened all users upgrading to as it includes lots of small fixes and quality of life improvements.
