### ISSUE TITLE
Feature request - Measure battery level on Enviro Weather

### ISSUE THREAD

**Issue by imascarenhas** [pimoroni/enviro#42]
Not sure if it is feasible directly or with an additional bit of circuitry, but please could we get measuring the battery (LiPo connected via the onboard JST-PH) level and reporting back with the rest of the data?

It is probably not needed to be at the same rate as the rest of the data so could be done daily, for example, or configurable on a separate interval.

**Comment by lowfatcode** [comment]
"voltage" has been added as a reading to the new version of the software - this will work on all Enviro boards.

Note that if you have the board plugged into USB then the voltage will be the USB supply, not the battery!
