### ISSUE TITLE
Blank WiFi networks in setup

### ISSUE THREAD

**Issue by Gadgetoid** [pimoroni/enviro#43]
Nameless networks (which I believe are coming directly out of WiFi scan verbatim) are showing up in the UI and are a little... odd!

Excuse the enormous image.

![image](https://user-images.githubusercontent.com/1746967/187719824-642af49f-e8dd-440a-9563-af21246fdb76.png)

**Comment by lowfatcode** [comment]
Fixed in https://github.com/pimoroni/enviro/pull/45
