### ISSUE TITLE
WiFi password with double quote

### ISSUE THREAD

**Issue by jwillikers** [pimoroni/enviro#5]
Hi, I noticed that WiFi passwords with double quotes aren't properly escaped when entered during the provisioning process. I checked the value in `config.py` and noticed it was truncated at the first double quote.

**Comment by lowfatcode** [comment]
Cor, this was a journey - it took me about four hours to pin down the exact cause and put together a small fix for it. https://github.com/pimoroni/enviro/commit/fc91b98a27c24c2980b0aec21159279cd1ad09ed

**Comment by jwillikers** [comment]
@lowfatcode Geez, ain't that just way? Thanks so much for the fix! Appreciate the time you put in to this.
