### ISSUE TITLE
On Version 0.0.7 of the Weather board, rain stops the system

### ISSUE THREAD

**Issue by MrDrem** [pimoroni/enviro#65]
Board was running fine with uploads every reading (and 5 minutes) until it started raining at 01:22 this morning. Log file here - 
[2022-09-05 log.txt](https://github.com/pimoroni/enviro/files/9487421/2022-09-05.log.txt).

I have checked through the board storage, and the rain.txt file doesn't exist. I strongly suspect that this is the cause of the issue. Directory listing here - 
![directory1](https://user-images.githubusercontent.com/4300216/188384197-6f182006-aa30-42d9-ac85-98fae70dda88.JPG)
![directory2](https://user-images.githubusercontent.com/4300216/188384200-c0ba7fa3-1e78-4103-8eed-689144862787.JPG)

**Comment by lowfatcode** [comment]
Thanks for finding this! Fixed in https://github.com/pimoroni/enviro/pull/66
