### ISSUE TITLE
documentation/getting-started.md describes MQTT and InfluxDB destinations identically

### ISSUE THREAD

**Issue by gclinch** [pimoroni/enviro#72]
documentation/getting-started.md describes both MQTT and InfluxDB destinations as:

`The most commonly used messaging protocol for the Internet of Things (IoT).`

InfluxDB should probably be described differently - perhaps as 'The Time Series Data Platform where developers build IoT, analytics, and cloud applications.' (to match with the description shown during provisioning step 4)

**Comment by lowfatcode** [comment]
Whoops - copy pasta fail! I'll modify to your suggested language, many thanks!
