### ISSUE TITLE
Unable to publish to MQTT

### ISSUE THREAD

**Issue by jctooley** [pimoroni/enviro#84]
I have updated the firmware in Enviro-Weather to 0.0.8 and I am unable to publish to an MQTT broker. After investigation it appears that the issue is related to the keepalive setting defaulting to 0.

**Comment by ZodiusInfuser** [comment]
There is a new release that should fix this issue: https://github.com/pimoroni/enviro/releases/tag/v0.0.9
I'll therefore close this but please re-open it or raise a new issue if you update and experience the problem again. Thanks
