### ISSUE TITLE
v0.0.8 no longer shows status codes/upload fail reasons with adafruit.io

### ISSUE THREAD

**Issue by helgibbons** [pimoroni/enviro#94]
Upload issues with adafruit.io would be much easier to diagnose if we could see the status codes/fail reasons like we could with earlier versions of the firmware. I suspect some reported issues are down to are throttling due to free account limits, particularly as we've now added a bunch more readings (Indoor now sends 8 data points by default rather than 5, which means sending more than 3 sets of readings at once will hit the 30 data points/minute limit).

**Comment by ZodiusInfuser** [comment]
There is a new release that fixes this issue: https://github.com/pimoroni/enviro/releases/tag/v0.0.9
I'll therefore close this but please re-open it or raise a new issue if you update and experience the problem again. Thanks
