### ISSUE TITLE
Rainfall not working on usb

### ISSUE THREAD

**Issue by jctooley** [pimoroni/enviro#96]
I have found on my weather board, that when the usb is connected the rainfall does not work. I believe this is due to the fact the pico does not go to sleep on usb.

Can anyone else confirm this?

**Comment by MrDrem** [comment]
This is covered under issue #70 I think. Its not got a Bug tag there yet, but I did conflate two issues in the one log.

**Comment by ZodiusInfuser** [comment]
There is a new release that should fix this issue, so I'm closing this: https://github.com/pimoroni/enviro/releases/tag/v0.0.9
Please re-open it or raise a new issue if you update and experience the problem again. Thanks
